# Generated by Django 5.1.1 on 2024-09-07 22:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('nombre', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Nombre Área')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Rut Cliente')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre Cliente')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido Cliente')),
                ('fecha_nacimiento', models.DateField(null=True, verbose_name='Fecha de Nacimiento Cliente')),
                ('telefono', models.PositiveIntegerField(verbose_name='Teléfono Cliente')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo Electrónico Cliente')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profile', verbose_name='Avatar Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Criticidad',
            fields=[
                ('nombre', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Nombre Criticidad')),
                ('valor', models.PositiveIntegerField(verbose_name='Valor')),
            ],
        ),
        migrations.CreateModel(
            name='EstadoTique',
            fields=[
                ('nombre', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Nombre EstadoTique')),
            ],
        ),
        migrations.CreateModel(
            name='TipoTique',
            fields=[
                ('nombre', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Nombre TipoTique')),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('nombre', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Nombre TipoUsuario')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=10, verbose_name='Rut Usuario')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre Usuario')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido Usuario')),
                ('fecha_nacimiento', models.DateField(null=True, verbose_name='Fecha de Nacimiento Usuario')),
                ('telefono', models.PositiveIntegerField(blank=True, null=True, verbose_name='Teléfono Usuario')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo Electrónico Usuario')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profile', verbose_name='Avatar Usuario')),
                ('login', models.BooleanField(blank=True, null=True, verbose_name='Login')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BaseTickets.area', verbose_name='Área de Usuario')),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BaseTickets.tipousuario', verbose_name='Tipo de Usuario')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tique',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID Tique')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('problema', models.TextField(verbose_name='Detalle Problema')),
                ('servicio', models.TextField(verbose_name='Detalle Servicio')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observación')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaseTickets.area', verbose_name='Área')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaseTickets.cliente', verbose_name='Rut Cliente')),
                ('criticidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaseTickets.criticidad', verbose_name='Estado')),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BaseTickets.estadotique', verbose_name='Estado')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaseTickets.tipotique', verbose_name='Tipo')),
                ('usuario_cierra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_usuario_cierra', to='BaseTickets.usuario', verbose_name='Usuario Cierra')),
                ('usuario_crea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_usuario_crea', to='BaseTickets.usuario', verbose_name='Usuario Crea')),
            ],
            options={
                'db_table': 'tique',
            },
        ),
    ]
