# Generated by Django 5.1.1 on 2024-12-06 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='ID Area')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre Area')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Rut Cliente')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre Cliente')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido Cliente')),
                ('fecha_nacimiento', models.DateField(null=True, verbose_name='Fecha de Nacimiento Cliente')),
                ('telefono', models.CharField(max_length=9, verbose_name='Teléfono Cliente')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo Electrónico Cliente')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profile', verbose_name='Avatar Cliente')),
                ('fecha_creacion', models.DateField(blank=True, null=True, verbose_name='Fecha registro cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Criticidad',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='ID criticidad')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre Criticidad')),
                ('valor', models.PositiveIntegerField(verbose_name='Valor')),
            ],
        ),
        migrations.CreateModel(
            name='EstadoTique',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='ID Estado Tique')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre EstadoTique')),
            ],
        ),
        migrations.CreateModel(
            name='TipoTique',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='ID tipo tique')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre TipoTique')),
            ],
        ),
        migrations.CreateModel(
            name='Tique',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='ID tique')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha creacion')),
                ('problema', models.TextField(verbose_name='Detalle Problema')),
                ('servicio', models.TextField(verbose_name='Detalle Servicio')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observación')),
                ('costo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Precio trabajo')),
                ('estadopago', models.BooleanField(blank=True, default=False, null=True, verbose_name='Estado pago')),
                ('fecha_cierre', models.DateField(blank=True, null=True, verbose_name='Fecha cierre')),
                ('name_crea', models.TextField(blank=True, null=True, verbose_name='Ultima modificacion crea')),
                ('name_cierre', models.TextField(blank=True, null=True, verbose_name='Ultima modificacion cierre')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaseTickets.area', verbose_name='Área')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaseTickets.cliente', verbose_name='Rut Cliente')),
                ('criticidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaseTickets.criticidad', verbose_name='Estado')),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BaseTickets.estadotique', verbose_name='Estado')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaseTickets.tipotique', verbose_name='Tipo')),
                ('usuario_cierra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_usuario_cierra', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Cierra')),
                ('usuario_crea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_usuario_crea', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Crea')),
            ],
            options={
                'db_table': 'tique',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=10, verbose_name='Rut Usuario')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre Usuario')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido Usuario')),
                ('fecha_nacimiento', models.DateField(null=True, verbose_name='Fecha de Nacimiento Usuario')),
                ('telefono', models.CharField(blank=True, max_length=9, null=True, verbose_name='Teléfono Usuario')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo Electrónico Usuario')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profile', verbose_name='Avatar Usuario')),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='Tipo de Usuario')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
