# Generated by Django 5.1.1 on 2024-12-07 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseTickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tique',
            name='costo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio trabajo'),
        ),
    ]
