# Generated by Django 5.1.1 on 2024-12-10 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BaseTickets', '0002_alter_tique_costo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criticidad',
            name='valor',
        ),
    ]
