# Generated by Django 5.1.1 on 2024-09-12 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseTickets', '0002_alter_tique_area_alter_tique_usuario_cierra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tique',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
