# Generated by Django 5.1.1 on 2024-09-12 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseTickets', '0003_alter_tique_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tique',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
