# Generated by Django 5.1 on 2024-09-28 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseTickets', '0004_alter_tique_fecha'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='area',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='Tipo de Usuario'),
        ),
        migrations.AlterField(
            model_name='tique',
            name='fecha',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha Tique'),
        ),
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.DeleteModel(
            name='TipoUsuario',
        ),
    ]
