# Generated by Django 5.1.1 on 2024-10-03 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BaseTickets', '0005_remove_usuario_area_alter_usuario_tipo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='login',
        ),
    ]
