# Generated by Django 5.1.1 on 2024-10-12 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BaseTickets', '0006_remove_usuario_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='tipo',
        ),
    ]
