# Generated by Django 5.1.1 on 2024-10-20 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseTickets', '0008_usuario_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=9, verbose_name='Teléfono Cliente'),
        ),
    ]
