# Generated by Django 5.1.1 on 2024-10-23 22:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseTickets', '0009_alter_cliente_telefono'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tique',
            old_name='fecha',
            new_name='fecha_cierre',
        ),
        migrations.AddField(
            model_name='tique',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha Tique'),
            preserve_default=False,
        ),
    ]
