# Generated by Django 5.1.1 on 2024-10-24 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseTickets', '0012_alter_usuario_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaTique',
            fields=[
                ('nombre', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Nombre Area')),
            ],
        ),
        migrations.AlterField(
            model_name='tique',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaseTickets.areatique', verbose_name='Área'),
        ),
    ]
