# Generated by Django 5.1.1 on 2024-10-25 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseTickets', '0013_areatique_alter_tique_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tique',
            name='fecha_cierre',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Tique'),
        ),
    ]
