# Generated by Django 5.1.1 on 2024-10-25 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseTickets', '0014_alter_tique_fecha_cierre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tique',
            name='fecha_cierre',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha cierre'),
        ),
        migrations.AlterField(
            model_name='tique',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha creacion'),
        ),
    ]
