# Generated by Django 5.1.1 on 2024-11-11 22:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseTickets', '0020_tique_name_cierre_tique_name_crea'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha registro cliente'),
            preserve_default=False,
        ),
    ]
