# Generated by Django 5.1.1 on 2024-11-12 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BaseTickets', '0022_alter_cliente_fecha_creacion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AreaTique',
            new_name='Area',
        ),
    ]
